version: "3"
services:
  nginx:
    image: "nginx:1.11.6-alpine"
    restart: on-failure
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build:/usr/share/nginx/html
